import json
import logging
from typing import AsyncIterator, List, Dict, Any

import httpx

logger = logging.getLogger(__name__)

class LLMClient:
    """
    An async LLM client for communicating with llama-server's OpenAI-compatible API.
    """

    def __init__(self, base_url: str = "http://localhost:8080", model: str = "qwen") -> None:
        """
        Initialize the LLM client.

        Args:
            base_url: The base URL of the llama-server API.
            model: The name of the model to use.
        """
        self.base_url = base_url
        self.model = model
        # Use a long timeout for CPU inference
        self.client = httpx.AsyncClient(timeout=360.0)

    async def chat_with_tools(self, messages: List[Dict[str, Any]], tools: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Send a non-streaming chat request with tools.
        Used for Pass 1 (tool decision).

        Args:
            messages: A list of message dictionaries.
            tools: A list of tool definition dictionaries.

        Returns:
            The complete response JSON dictionary.
        
        Raises:
            ConnectionError: If the server is unreachable.
            RuntimeError: If the API returns an error response.
        """
        payload = {
            "model": self.model,
            "messages": messages,
            "tools": tools,
            "stream": False
        }
        
        try:
            response = await self.client.post(
                f"{self.base_url}/v1/chat/completions",
                json=payload
            )
            response.raise_for_status()
            return response.json()
        except httpx.RequestError as e:
            logger.error(f"Failed to connect to LLM server: {e}")
            raise ConnectionError(f"Failed to connect to LLM server at {self.base_url}: {e}")
        except httpx.HTTPStatusError as e:
            logger.error(f"LLM server returned an error: {e.response.text}")
            raise RuntimeError(f"LLM API error: {e.response.status_code} - {e.response.text}")

    async def chat_stream(self, messages: List[Dict[str, Any]]) -> AsyncIterator[str]:
        """
        Send a streaming chat request.
        Used for Pass 2 (final answer generation).

        Args:
            messages: A list of message dictionaries.

        Yields:
            Token strings generated by the model.
        
        Raises:
            ConnectionError: If the server is unreachable.
            RuntimeError: If the API returns an error response.
        """
        payload = {
            "model": self.model,
            "messages": messages,
            "stream": True
        }
        
        try:
            async with self.client.stream(
                "POST", 
                f"{self.base_url}/v1/chat/completions", 
                json=payload
            ) as response:
                response.raise_for_status()
                async for line in response.aiter_lines():
                    line = line.strip()
                    if not line:
                        continue
                    
                    if line.startswith("data: "):
                        data_str = line[6:]
                        if data_str == "[DONE]":
                            break
                        
                        try:
                            data_json = json.loads(data_str)
                            choices = data_json.get("choices", [])
                            if choices:
                                delta = choices[0].get("delta", {})
                                content = delta.get("content")
                                if content is not None:
                                    yield content
                        except json.JSONDecodeError:
                            logger.warning(f"Failed to parse SSE line: {line}")
        except httpx.RequestError as e:
            logger.error(f"Failed to connect to LLM server during stream: {e}")
            raise ConnectionError(f"Failed to connect to LLM server at {self.base_url}: {e}")
        except httpx.HTTPStatusError as e:
            logger.error(f"LLM server returned an error during stream: {e}")
            raise RuntimeError(f"LLM API stream error: {e.response.status_code}")

    async def close(self) -> None:
        """
        Close the underlying httpx client.
        """
        await self.client.aclose()
